//CORE_REFERENCE_IMPORTS
//CORE_REFERENCE_IMPORT-ok-SSD_SERVICE_ID_sd_xD1ZK2GzZmyzfDTk
import { ok as SSD_SERVICE_ID_sd_xD1ZK2GzZmyzfDTk } from './sd-services/ok';

export const UserRoutes = [
    //CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-ok-SSD_SERVICE_ID_sd_xD1ZK2GzZmyzfDTk
SSD_SERVICE_ID_sd_xD1ZK2GzZmyzfDTk,
];
